services:
  db:
    image: database:1.0.0
    container_name: postgres-db
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d database"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10

  auth-service:
    container_name: auth-service
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=database
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=ThisIsASecretKeyForFreelanSearchPlatformMustBe256BitsLong!
      - JWT_EXPIRATION_MS=86400000
    depends_on:
      db:
        condition: service_healthy

  profile-service:
    container_name: profile-service
    build:
      context: ./profile-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=database
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=ThisIsASecretKeyForFreelanSearchPlatformMustBe256BitsLong!
    depends_on:
      db:
        condition: service_healthy
 
  listings-service:
    container_name: listings-service
    build:
      context: ./listings-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=database
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=ThisIsASecretKeyForFreelanSearchPlatformMustBe256BitsLong!
      - JWT_EXPIRATION_MS=86400000
    depends_on:
      db:
        condition: service_healthy

  bff:
    container_name: bff
    build:
      context: ./bff
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8081
      - PROFILE_SERVICE_URL=http://profile-service:8082
      - LISTINGS_SERVICE_URL=http://listings-service:8083
    depends_on:
      - auth-service
      - profile-service
      - listings-service

volumes:
  postgres_data:
    name: "postgres_data"
