spring.application.name=listings-service
server.port=8083

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:database}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET:ThisIsASecretKeyForFreelanSearchPlatformMustBe256BitsLong!}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
management.tracing.sampling.probability=1.0
