spring.application.name=bff
spring.main.web-application-type=servlet
server.port=8080

# URL микросервиса авторизации
services.auth.url=${AUTH_SERVICE_URL:http://auth-service:8081}

# URL микросервиса профилей
services.profile.url=${PROFILE_SERVICE_URL:http://profile-service:8082}

# URL микросервиса объявлений
services.listings.url=${LISTINGS_SERVICE_URL:http://listings-service:8083}
