input {
  # HTTP (5044) - ручные логи (и теперь frontend)
  http {
    port => 5044
    codec => json
    add_field => { "[@metadata][source]" => "frontend" }
  }
}
output {
  if [@metadata][source] == "frontend" {
    elasticsearch { 
      hosts => ["elasticsearch:9200"] 
      index => "frontend-logs-%{+YYYY.MM.dd}" 
    }
  }
}
