input{
tcp {
  port => 5045
  codec => "json_lines"
  add_field => { "[@metadata][source]" => "bff" }
}
tcp {
  port => 5046
  codec => "json_lines"
  add_field => { "[@metadata][source]" => "auth-service" }
}

}
output {
  if [@metadata][source] == "bff" {
    elasticsearch { hosts => ["elasticsearch:9200"] index => "bff-logs-%{+YYYY.MM.dd}" }
  }
  else if [@metadata][source] == "auth-service" {
    elasticsearch { hosts => ["elasticsearch:9200"] index => "auth-service-logs-%{+YYYY.MM.dd}" }
  }

}
