input {
  # HTTP (5044) - ручные логи
  http {
    port => 5044
    codec => json
    add_field => { "[@metadata][source]" => "http" }
  }

  # TCP (5045) - FastAPI логи (и через Nginx, и напрямую)
  tcp {
    port => 5045
    codec => "json_lines"
    add_field => { "[@metadata][source]" => "fastapi" }
  }

  # SYSLOG (5146) - Nginx логи (UDP)
  syslog {
    port => 5146
    add_field => { "[@metadata][source]" => "nginx" }
  }
}

output {
  if [@metadata][source] == "http" {
    elasticsearch { 
      hosts => ["elasticsearch:9200"] 
      index => "http-logs-%{+YYYY.MM.dd}" 
    }
  } else if [@metadata][source] == "fastapi" {
    elasticsearch { 
      hosts => ["elasticsearch:9200"] 
      index => "fastapi-logs-%{+YYYY.MM.dd}" 
    }
  } else if [@metadata][source] == "nginx" {
    elasticsearch { 
      hosts => ["elasticsearch:9200"] 
      index => "nginx-logs-%{+YYYY.MM.dd}" 
    }
  }
}
