input {
  # HTTP (5044) - для ручной отправки логов напрямую в logstash через curl 
  http {
    port => 5044
    codec => json
    response_headers => {
      "Content-Type" => "text/plain"
    }
    response_code => 200
    add_field => { "[@metadata][source]" => "http" } # Метка для роутинга
  }

  # TCP (5045) - основной канал для FastAPI логов
  tcp {
    port => 5045
    codec => "json_lines"
    add_field => { "[@metadata][source]" => "tcp" } # Метка для роутинга
  }
  tcp {
    port => 5046
    codec => "json_lines"
    add_field => { "[@metadata][source]" => "nginx-tcp" } # Метка для роутинга
  }
}

output {
  # Разделяем логи по источникам для разных индексов Elasticsearch
  if [@metadata][source] == "http" {
    # Логи из HTTP-источника (ручные запросы)
    elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "http-logs-%{+YYYY.MM.dd}"
    }
  } else if [@metadata][source] == "tcp" {
    # Логи из TCP-источника (FastAPI)
    elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "tcp-logs-%{+YYYY.MM.dd}"
    }
  } else if [@metadata][source] == "nginx-tcp" {
    # Логи из TCP-источника (NGINX)
    elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "nginx-tcp-logs-%{+YYYY.MM.dd}"
    }
    
  }
  

}
